[package]
name = "rust-notifications"
description = "Library for sending iOS and Android push notifications"
homepage = "https://comm.app"
version = "0.1.0"
license = "BSD-3-Clause"
edition = "2021"

[dependencies]
tracing = "0.1"
tokio = { version = "1.14", features = ["rt-multi-thread"]}
lazy_static = "1.4"
a2 = "0.6"
cxx = "1.0"
log = "0.4"
fcm = "0.9"

[build-dependencies]
cxx-build = "1.0"

[lib]
crate-type=["staticlib"]
