[package]
name = "rust-notifications"
description = "Library for sending iOS and Android push notifications"
homepage = "https://comm.app"
version = "0.1.0"
license = "BSD-3-Clause"
edition = "2021"

[dependencies]

[lib]
crate-type=["staticlib"]
