[package]
name = "opaque-ke-cxx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = "0.3"
opaque-ke = "1.2.0"
curve25519-dalek = "3"
rand = "0.8"
sha2 = "0.9"
digest = "0.9"
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

[lib]
crate-type = ["staticlib"]
